import os

FINNHUB_API_KEY = os.getenv("FINNHUB_API_KEY") or "d2f3fq9r01qj3egr0apgd2f3fq9r01qj3egr0aq0"

PRICE_MIN = 2.0
PRICE_MAX = 70.0
MIN_PCT_CHANGE = 3.6
MIN_REL_VOL = 2.5
NEWS_LOOKBACK_MIN = 480

MODE = "EITHER"

LOG_TO_CSV = True
LOG_PATH = "logs/hits.csv"

DISCORD_WEBHOOK_URL = os.getenv("DISCORD_WEBHOOK_URL", "").strip()
TELEGRAM_BOT_TOKEN  = os.getenv("TELEGRAM_BOT_TOKEN", "").strip()
TELEGRAM_CHAT_ID    = os.getenv("TELEGRAM_CHAT_ID", "").strip()

SCAN_BATCH = 150
SLEEP_SECONDS = 2.0

PREPOST_PROGRESS = 0.20
REGULAR_SESSION_START_ET = "09:30"
REGULAR_SESSION_END_ET   = "16:00"

WATCHLIST_ONLY = False
WATCHLIST = []